/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

/**
 *
 * @author JaviBl8
 */
public class TamanoLienzo extends javax.swing.JDialog {
    
    Boolean enviar=false;
    double ancho, alto;
    /**
     * Creates new form Nuevo
     */
    public TamanoLienzo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAncho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAlto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Introduzca el tamaño que desea que tenga el lienzo");
        getContentPane().add(jLabel1);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel3.setText("Ancho");
        jPanel1.add(jLabel3);
        jPanel1.add(jTextFieldAncho);

        jLabel2.setText("Alto");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldAlto);

        getContentPane().add(jPanel1);

        jButton1.setText("Enviar");
        jButton1.setMaximumSize(new java.awt.Dimension(30, 32));
        jButton1.setMinimumSize(new java.awt.Dimension(30, 32));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ancho = Integer.parseInt(this.jTextFieldAncho.getText());
        alto = Integer.parseInt(this.jTextFieldAlto.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAlto;
    private javax.swing.JTextField jTextFieldAncho;
    // End of variables declaration//GEN-END:variables
}
