/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Hay que borrar todos los sitios donde pone lienzo2D y cambiarlo por lienzo2D image
//Hay que quitar el lienzo2d y poner un panel scroll para que cuando la imagen sea grande aparezcan las barras de scroll
package practica7;

import javafx.scene.paint.Color;
import sm.jbl.herramientas.Herramientas;
import sm.jbl.iu.LienzoImagen2D;

/**
 *
 * @author JaviBl8
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    VentanaPrincipal parentPrincipal;
    int indiceColores=0;
    
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        
        try {
            this.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
        this.parentPrincipal = parent;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        lienzoImagen2D = new sm.jbl.iu.LienzoImagen2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        setName(""); // NOI18N
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane.setPreferredSize(new java.awt.Dimension(500, 350));

        javax.swing.GroupLayout lienzoImagen2DLayout = new javax.swing.GroupLayout(lienzoImagen2D);
        lienzoImagen2D.setLayout(lienzoImagen2DLayout);
        lienzoImagen2DLayout.setHorizontalGroup(
            lienzoImagen2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        lienzoImagen2DLayout.setVerticalGroup(
            lienzoImagen2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(lienzoImagen2D);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        Herramientas herramienta = lienzoImagen2D.getHerramienta();
        parentPrincipal.buttonGroup.clearSelection();
        //Botones herramientas
        switch(herramienta){
            case LAPIZ:               
                parentPrincipal.jToggleButtonLapiz.setSelected(true);
                parentPrincipal.jLabelEstado.setText("Lápiz");
                break;
            case RECTANGULO:                
                parentPrincipal.jToggleButtonRectangulo.setSelected(true);
                parentPrincipal.jLabelEstado.setText("Rectángulo");
                break;
            case LINEA:                
                parentPrincipal.jToggleButtonLinea.setSelected(true);
                parentPrincipal.jLabelEstado.setText("Línea");
                break;
            case CIRCULO:                
                parentPrincipal.jToggleButtonOvalo.setSelected(true);
                parentPrincipal.jLabelEstado.setText("Círculo");
                break;
        }    
        parentPrincipal.buttonGroupOpciones.clearSelection();
       
        //Botones propiedades
        if(lienzoImagen2D.getEditar()){
            parentPrincipal.jToggleButtonEditar.setSelected(true);
            if(lienzoImagen2D.getRellenar()){
                parentPrincipal.jToggleButtonRelleno.setSelected(true);
            }
            if(lienzoImagen2D.getAlisar()){
                parentPrincipal.jToggleButtonAlisado.setSelected(true);
            }
            if(lienzoImagen2D.getTransparentar()){
                parentPrincipal.jToggleButtonTransparencia.setSelected(true);
            }
        }
        
        //Colores
        parentPrincipal.jComboBoxColores.setSelectedIndex(indiceColores);
        
    }//GEN-LAST:event_formInternalFrameActivated
    
    public LienzoImagen2D getLienzo(){
        return lienzoImagen2D;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private sm.jbl.iu.LienzoImagen2D lienzoImagen2D;
    // End of variables declaration//GEN-END:variables
}
